FROM livox_ros2:humble

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /home/devuser/ros2_ws/src
RUN git clone https://github.com/Ericsii/FAST_LIO.git --recursive
RUN cd .. \
    && bash -c "source /opt/ros/humble/setup.bash \
        && source ../livox_ws/install/setup.bash \
        && sudo apt-get update \
        && rosdep update \
        && rosdep install --from-paths src ../livox_ws/src --ignore-src -y \
        && colcon build --symlink-install" \
    && bash -c "source ./install/setup.bash"

COPY launch/run.sh launch/fast_lio_MID360_launch.py launch/playbag_fast_lio_MID360_launch.py ./
